spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_wiki
    username: root
    password: testme
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
